[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "euler828"
version = "0.1.0"
requires-python = ">=3.6"

[project.optional-dependencies]
dev = ["pytest ~= 7.1.2"]